server:
  port: 8081

spring:
  jmx:
    enabled: true
  zipkin:
      base-url: http://localhost:9411

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: Thakur@7

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
    name: PAYMENT-SERVICE

  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    sampling:
      probability: 1.0
